package normalize_test

import (
	"bytes"
	"math/big"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"testing"

	"github.com/jonstump/nms-base-planner/internal/domain"
)

// Governing: ADR-0001 (two-tier NMS data ingestion), SPEC-0004 REQ
// "Acceptance Against the Golden Tree", REQ "Source Provenance and Version
// Stamping"
//
// The Stasis Device tree resolved from a real generated artifact. A test
// that resolves it from `stasis-device.tier1.json` verifies the rollup
// engine, which #2 already did; only a test whose input the normalizer
// produced verifies the normalizer.

// committedArtifact is the generated dataset, regenerated by cmd/nmstier1
// and committed per SPEC-0004 REQ "Deterministic Output".
const committedArtifact = "../../data/tier1.json"

// The tree ADR-0001 confirmed by hand, by game ID. Thirty-four of these are
// the nodes the hand-authored fixture carries; CAVE1 and OXYGEN are the two
// it does not — see TestGeneratedTreeIsThirtySixNodesNotThirtyFour.
var stasisTree = []string{
	"ULTRAPROD2",                       // Stasis Device
	"MEGAPROD2", "MEGAPROD3", "ALLOY8", // the three branches
	"COMPOUND5", "COMPOUND6", "COMPOUND2", "COMPOUND3", // Superconductor, Cryo-Pump, Semiconductor, Hot Ice
	"REACTION1", "REACTION2", "REACTION3", // Thermic Condensate, Enriched Carbon, Nitrogen Salt
	"FARMPROD8", "FARMPROD9", "FARMPROD2", "FARMPROD3", "FARMPROD4", "FARMPROD5",
	"ALLOY1", "ALLOY5", "ALLOY6", "CAVE2",
	"GAS1", "GAS2", "GAS3", "FUEL2",
	"PLANT_SNOW", "PLANT_HOT", "PLANT_DUST", "PLANT_LUSH", "PLANT_RADIO", "PLANT_POOP",
	"LUSH1", "HOT1", "COLD1",
	"CAVE1", "OXYGEN", // reached because Ionised Cobalt is refined, not gathered
}

func loadCommitted(t *testing.T) *domain.Tier1 {
	t.Helper()
	f, err := os.Open(committedArtifact)
	if err != nil {
		t.Fatalf("opening the committed artifact: %v", err)
	}
	defer f.Close()
	a1, err := domain.LoadTier1(f)
	if err != nil {
		t.Fatalf("loading the committed artifact: %v", err)
	}
	return a1
}

// SPEC-0004 REQ "Acceptance Against the Golden Tree":
// WHEN the rollup engine resolves ULTRAPROD2 at quantity 1 from a generated
// artifact THEN it returns the confirmed tree and leaf totals.
//
// Runs against the committed artifact so CI exercises it without game files.
// The gated test below proves that artifact is what the normalizer produces.
func TestCommittedArtifactReproducesTheGoldenTree(t *testing.T) {
	a1 := loadCommitted(t)
	if !a1.Extracted {
		t.Error("the committed artifact is not marked extracted")
	}
	if a1.Provenance == nil || a1.Provenance.MBINCompiler == "" {
		t.Error("the committed artifact carries no provenance")
	}

	g, err := domain.Resolve(a1, domain.PlanInput{Target: "ULTRAPROD2", Quantity: 1})
	if err != nil {
		t.Fatalf("resolving the Stasis Device: %v", err)
	}
	assertGoldenTree(t, g)
}

// The three branches ADR-0001 names, and the quantities it confirmed.
func assertGoldenTree(t *testing.T, g *domain.ResolvedGraph) {
	t.Helper()

	if got, want := len(g.Nodes), len(stasisTree); got != want {
		t.Errorf("resolved %d nodes, want %d", got, want)
	}
	for _, id := range stasisTree {
		if _, ok := g.Node(id); !ok {
			t.Errorf("%s missing from the resolved tree", id)
		}
	}
	// Distinct, not merely counted: a repeated node would satisfy a count.
	seen := map[string]bool{}
	for _, n := range g.Nodes {
		if seen[n.ItemID] {
			t.Errorf("%s appears twice in the node list", n.ItemID)
		}
		seen[n.ItemID] = true
	}

	// The Stasis Device takes one of each branch.
	sd, _ := g.Node("ULTRAPROD2")
	var branches []string
	for _, e := range sd.Children {
		branches = append(branches, e.To)
		if e.PerUnit != 1 {
			t.Errorf("Stasis Device consumes %d of %s, want 1", e.PerUnit, e.To)
		}
	}
	sort.Strings(branches)
	if want := []string{"ALLOY8", "MEGAPROD2", "MEGAPROD3"}; !equalStrings(branches, want) {
		t.Errorf("branches = %v, want %v", branches, want)
	}

	// Each gas product costs 250 gas and 50 Condensed Carbon.
	gases := map[string]string{"REACTION1": "GAS1", "REACTION2": "GAS2", "REACTION3": "GAS3"}
	for product, gas := range gases {
		n, ok := g.Node(product)
		if !ok {
			t.Errorf("%s missing", product)
			continue
		}
		costs := map[string]int64{}
		for _, e := range n.Children {
			costs[e.To] = e.PerUnit
		}
		if costs[gas] != 250 {
			t.Errorf("%s consumes %d %s, want 250", product, costs[gas], gas)
		}
		if costs["FUEL2"] != 50 {
			t.Errorf("%s consumes %d Condensed Carbon, want 50", product, costs["FUEL2"])
		}
	}

	// The leaf totals at quantity 1.
	wantLeaves := map[string]int64{
		"GAS1": 500, "GAS2": 500, "GAS3": 500, // Sulphurine, Radon, Nitrogen
		"FUEL2": 300, // Condensed Carbon
	}
	for id, want := range wantLeaves {
		n, ok := g.Node(id)
		if !ok {
			t.Errorf("%s missing from the tree", id)
			continue
		}
		if !n.Terminal {
			t.Errorf("%s is not a terminal; it expanded into %d children", id, len(n.Children))
		}
		got, exact := n.TotalInt()
		if !exact || got != want {
			t.Errorf("%s total = %s (exact=%v), want %d", id, n.Total().RatString(), exact, want)
		}
	}

}

// The tree is 36 nodes, not the 34 ADR-0001 records.
//
// The two extra are `CAVE1` (Cobalt) and `OXYGEN`, reached because
// `CAVE2` (Ionised Cobalt) is refined rather than gathered — its
// `PinObjective` reads `UI_REFINE_OBJ` — so it expands into 2 Cobalt and
// 2 Oxygen instead of terminating. The hand-authored fixture models it as a
// raw leaf, which was a prototype simplification rather than a fact about
// the game.
//
// Asserted explicitly rather than folded into the count above, so the
// difference stays a recorded finding instead of a number someone quietly
// changed.
func TestGeneratedTreeIsThirtySixNodesNotThirtyFour(t *testing.T) {
	a1 := loadCommitted(t)
	g, err := domain.Resolve(a1, domain.PlanInput{Target: "ULTRAPROD2", Quantity: 1})
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Nodes) != 36 {
		t.Fatalf("resolved %d nodes, want 36", len(g.Nodes))
	}

	ion, ok := g.Node("CAVE2")
	if !ok {
		t.Fatal("CAVE2 missing")
	}
	if ion.Terminal {
		t.Fatal("CAVE2 terminated; the extra two nodes are supposed to come from expanding it")
	}
	kids := map[string]int64{}
	for _, e := range ion.Children {
		kids[e.To] = e.PerUnit
	}
	if kids["CAVE1"] != 2 || kids["OXYGEN"] != 2 {
		t.Errorf("CAVE2 expands to %v, want 2 CAVE1 and 2 OXYGEN", kids)
	}

	// Pinning CAVE2 to raw is not available — it is not raw-obtainable —
	// which is what makes the extra two nodes structural rather than a
	// default the plan could opt out of.
	if _, err := domain.Resolve(a1, domain.PlanInput{
		Target:   "ULTRAPROD2",
		Quantity: 1,
		Methods:  map[string]domain.Method{"CAVE2": domain.MethodRaw},
	}); err == nil {
		t.Error("CAVE2 accepted method raw; the source says it is refined only")
	}
}

// SPEC-0001 REQ "Quantity Propagation and Aggregation" — totals scale
// linearly, checked over generated data rather than over the fixture.
func TestGeneratedTreeScalesLinearly(t *testing.T) {
	a1 := loadCommitted(t)

	one, err := domain.Resolve(a1, domain.PlanInput{Target: "ULTRAPROD2", Quantity: 1})
	if err != nil {
		t.Fatal(err)
	}
	ten, err := domain.Resolve(a1, domain.PlanInput{Target: "ULTRAPROD2", Quantity: 10})
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range one.Nodes {
		scaled, ok := ten.Node(n.ItemID)
		if !ok {
			t.Errorf("%s missing at quantity 10", n.ItemID)
			continue
		}
		want := new(big.Rat).Mul(n.Total(), big.NewRat(10, 1))
		if scaled.Total().Cmp(want) != 0 {
			t.Errorf("%s at ×10 = %s, want %s", n.ItemID, scaled.Total().RatString(), want.RatString())
		}
	}
}

// SPEC-0004 REQ "Source Provenance and Version Stamping" — "The normalizer
// MUST be able to reproduce any committed artifact from the same install
// without manual steps."
//
// This is the test the story exists for: it generates the artifact in this
// run and compares it byte for byte with the committed one. Gated on a real
// decompiled install so CI stays green without game files.
//
//	NMS_SOURCE_DIR=/path/to/decompiled go test ./internal/normalize/ -run Reproduces -v
func TestRealInstallReproducesTheCommittedArtifact(t *testing.T) {
	root := os.Getenv("NMS_SOURCE_DIR")
	if root == "" {
		t.Skip("NMS_SOURCE_DIR is not set; skipping regeneration against a real install")
	}

	committed, err := os.ReadFile(committedArtifact)
	if err != nil {
		t.Fatal(err)
	}
	version := gameVersionOf(t, committed)

	out := filepath.Join(t.TempDir(), "tier1.json")
	cmd := exec.Command("go", "run", "../../cmd/nmstier1",
		"-src", root, "-out", out, "-game-version", version)
	if blob, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("nmstier1: %v\n%s", err, blob)
	}

	regenerated, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(committed, regenerated) {
		t.Errorf("the regenerated artifact differs from the committed one (%d bytes vs %d); "+
			"either the install changed or the committed file was hand-edited",
			len(regenerated), len(committed))
	}

	// And the tree it produces is the confirmed one — asserted on the
	// freshly generated value, not on the committed file, so this test
	// stands on its own if the two ever diverge.
	f, err := os.Open(out)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	a1, err := domain.LoadTier1(f)
	if err != nil {
		t.Fatalf("loading the regenerated artifact: %v", err)
	}
	g, err := domain.Resolve(a1, domain.PlanInput{Target: "ULTRAPROD2", Quantity: 1})
	if err != nil {
		t.Fatalf("resolving from the regenerated artifact: %v", err)
	}
	assertGoldenTree(t, g)
}

// gameVersionOf reads the committed artifact's game_version, so the
// regeneration stamps the same build rather than a hard-coded one.
func gameVersionOf(t *testing.T, blob []byte) string {
	t.Helper()
	a1, err := domain.LoadTier1(bytes.NewReader(blob))
	if err != nil {
		t.Fatal(err)
	}
	return a1.GameVersion
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
